---
- name: run sysctl
  command: sysctl --load=/etc/sysctl.d/10-disable-ipv6.conf

- name: Reboot host
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 10
    reboot_timeout: 600
    post_reboot_delay: 15

- name: restart systemd-logind
  service:
    name: systemd-logind
    state: restarted
  when: >
    ansible_service_mgr == 'systemd'

- name: reload systemd
  systemd:
    state: restarted
    daemon_reload: yes
    name: crond
