---
molecule:
  raw_ssh_args:
    - -o StrictHostKeyChecking=false
    - -o UserKnownHostsFile=/dev/null
ansible:
  host_key_checking: False
  raw_ssh_args:
    - -o UserKnownHostsFile=/dev/null
    - -o IdentitiesOnly=yes
    - -o ControlMaster=auto
    - -o ControlPersist=60s
dependency:
  name: galaxy
  options:
    ignore-certs: True
    ignore-errors: True
    role-file: requirements.yml
    force: False
lint: |
  set -e
  pre-commit run --all-files
driver:
  name: docker
platforms:
  - name: instance1-$TOX_ENVNAME
    image: "${MOLECULE_DISTRO:-centos:8}"
    privileged: True
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    command: "${MOLECULE_DOCKER_COMMAND}"
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN
    tty: true
    env:
      container: docker

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_enabled: profile_tasks, timer, yaml
verifier:
  name: ansible
scenario:
  create_sequence:
    - dependency
    - create
  check_sequence:
    - dependency
    - destroy
    - create
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - lint
    - dependency
    - destroy
    - create
    - converge
    - idempotence
    - verify
    - destroy
