---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: set ansible_python_interpreter to "/usr/bin/python3" on fedora
      set_fact:
        ansible_python_interpreter: "/usr/bin/python3"
      when: ansible_facts.distribution == 'Fedora'

    - name: Run the equivalent of "apt update && apt upgrade"
      apt:
        name: "*"
        state: latest
        update_cache: true
      when: ansible_facts.os_family == 'Debian'

    - name: install required tools on SuSE
      # cannot use zypper module, since it depends on python-xml
      shell: "zypper -n install python-xml"
      when: ansible_facts.os_family == 'Suse'

    - name: install required tools on fedora
      dnf:
        name:
          - python
          - findutils
          - procps-ng
          - openssh-server
      when: ansible_facts.distribution == 'Fedora'

    - name: install required tools on CentOS
      dnf:
        name:
          - openssh-server
          - openssh-clients
      when: ansible_facts.distribution == 'CentOS'

    - name: install required tools on RHEL
      yum:
        name:
          - openssh-clients
          - openssh
        state: present
        update_cache: true
      ignore_errors: true
