---
- name: Verify
  hosts: all
  become: yes
  gather_facts: true

  tasks:
    - name: check if connection still works
      ping:
    - name: Check that the 10-disable-ipv6.j2 exists
      stat:
        path: /etc/sysctl.d/10-disable-ipv6.conf
      register: ipv6_result
    - name: Check that the 00-rsyslog-iptables.j2 exists
      stat:
        path: /etc/rsyslog.d/00-rsyslog-iptables.conf
      register: rsyslog_log_result
    - name: Check that the /etc/rsyslog.conf exists
      stat:
        path: /etc/rsyslog.conf
      register: rsyslog_result
    - name: Fail if 10-disable-ipv6.conf file is not present
      fail:
        msg: The system may not be provisioned according.
      when:
        - (not ipv6_result.stat.exists)
    - name: Fail if 00-rsyslog-iptables.conf not present
      fail:
        msg: The system may not be provisioned according.
      when:
        - (not rsyslog_log_result.stat.exists)
    - name: Fail if /etc/rsyslog.conf not present
      fail:
        msg: The system may not be provisioned according.
      when:
        - (not rsyslog_result.stat.exists)
