---
- name: Verify
  hosts: all
  become: yes
  gather_facts: true

  tasks:
    - name: check if connection still works
      ping:
    - name: Check if the 10-disable-ipv6.j2 exists
      stat:
        path: /etc/sysctl.d/10-disable-ipv6.conf
      register: ipv6_result
    - name: Fail if 10-disable-ipv6.conf file is present by default
      fail:
        msg: The system may not be provisioned according.
      when:
        - ipv6_result.stat.exists
