# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Ansible Role Bootstrap Galaxy publish

on:
  release:
    types: [ created, edited, published, released ]

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: galaxy
        uses: robertdebock/galaxy-action@1.1.0
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
